name: Plan and Apply Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'target environment name'
        required: true
        type: choice
        options:
          - development
          - qa
          - production
        default: 'development'

jobs:
  Plan-Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Terraform Plan
        run: |
           echo "Running Terraform plan"

  Apply-Terraform:
    runs-on: ubuntu-latest
    needs: Plan-Terraform
    # environment:
    #   name: dev  # Use the environment you set up (e.g., 'production')
      # url: https://example.com # Optional, link to the deployment for visibility
    
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: supriya5643
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Apply Terraform
        run: |
           echo "Applying Terraform"

